### ISSUE TITLE
Failed at the mcrypt@0.0.13 install script

### ISSUE THREAD

**Issue by thinkv** [tugrul/node-mcrypt#17]
Hi guys, trying to compile on heroku, seem to keep getting this?

any ideas?

thanks!
-----> Building Meteor App Bundle
       npm-container: updating npm dependencies -- jscryptor, mcrypt...
       npm WARN package.json packages-for-meteor-smartpackage-1dwsjqb@0.0.0 No
       description
       npm WARN package.json packages-for-meteor-smartpackage-1dwsjqb@0.0.0 No
       repository field.
       npm WARN package.json packages-for-meteor-smartpackage-1dwsjqb@0.0.0 No README
       data
       In file included from ../src/mcrypt.cc:3:0:
       ../src/mcrypt.h:10:20: fatal error: mcrypt.h: No such file or directory
       #include <mcrypt.h>
       ^
       compilation terminated.
       make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit

**Comment by tugrul** [comment]
Error says: "Looks like libmcrypt and header files are missing." 

I don't have an idea how can you prepare this build dependencies on heroku.

Please notify me if you resolve problem and find solution. I'm going to update DOC file

Thanks

**Comment by thinkv** [comment]
:( Im quite new to this, not really sure where to go from here, i tried to install the libraries first on heroku using https://github.com/ddollar/heroku-buildpack-apt
However it still gets the same error.

**Comment by biswasrj** [comment]
Hi. I am getting similar errors while I try to install it in centos.
I've also installed build tools with node using.. `yum install gcc-c++ make`
Can you plz identify where I'm doing it wrong?

The error list is long... starts with...
```/
> mcrypt@0.0.13 install /root/node_modules/mcrypt
> node-gyp rebuild --release

make: Entering directory `/root/node_modules/mcrypt/build'
  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:10:20: warning: mcrypt.h: No such file or directory
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:27: error: expected '>' before '(' token
../src/mcrypt.h:57: error: 'MCRYPT' does not name a type
../src/mcrypt.cc: In constructor 'MCrypt::MCrypt(const v8::Arguments&)':
../src/mcrypt.cc:17: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:17: error: 'mcrypt_module_open' was not declared in this scope
../src/mcrypt.cc: In destructor 'virtual MCrypt::~MCrypt()':
../src/mcrypt.cc:21: error: 'mcrypt_' was not declared in this scope
../src/mcrypt.cc:21: error: 'mcrypt_module_close' was not declared in this scope
../src/mcrypt.cc: At global scope:
../src/mcrypt.cc:25: error: expected '>' before '(' token
../src/mcrypt.cc: In member function 'char* MCrypt::transform(const char*, size_t*, int*)':
.....
.....
```
the end part...
```
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
make: Leaving directory `/root/node_modules/mcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab104.1
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /root/node_modules/mcrypt
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! mcrypt@0.0.13 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mcrypt@0.0.13 install script.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab104.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "mcrypt"
npm ERR! cwd /root
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

> mcrypt@0.0.13 preuninstall /root/node_modules/mcrypt
> rm -rf build/*

npm ERR! not ok code 0
```

Thanks

**Comment by biswasrj** [comment]
update: it installed in Ubuntu without any error!
Thanks.

**Comment by biswasrj** [comment]
but there's problem in centos installation.

**Comment by tugrul** [comment]
@biswasrj have you ever install libmcrypt and libmcrypt-dev packages. I don't know these packages are there in the official repo of centos.

There is a topic about on centos forum about these packages. 
https://www.centos.org/forums/viewtopic.php?t=4880

**Comment by hrajchert** [comment]
I have a similar problem installing on aws ami

I've done `yum install libmcrypt libmcrypt-devel`
and ` yum install gcc-c++ make`
```
In file included from /home/ec2-user/.node-gyp/0.11.12/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
/home/ec2-user/.node-gyp/0.11.12/deps/v8/include/v8.h: In member function ‘void v8::ReturnValue<T>::Set(uint32_t)’:
/home/ec2-user/.node-gyp/0.11.12/deps/v8/include/v8.h:5816:31: warning: typedef ‘I’ locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
In file included from ../src/mcrypt.h:9:0,
                 from ../src/mcrypt.cc:3:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:70:9: error: ‘UnboundScript’ in namespace ‘v8’ does not name a type
 typedef v8::UnboundScript      NanUnboundScript;
         ^
In file included from ../node_modules/nan/nan.h:82:0,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
../node_modules/nan/nan_new.h:181:16: error: ‘UnboundScript’ is not a member of ‘v8’
 struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
                ^
../node_modules/nan/nan_new.h:181:16: error: ‘UnboundScript’ is not a member of ‘v8’
../node_modules/nan/nan_new.h:181:33: error: template argument 1 is invalid
 struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
                                 ^
../node_modules/nan/nan_new.h:181:49: error: ‘UnboundScript’ is not a member of ‘v8’
 struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
                                                 ^
../node_modules/nan/nan_new.h:181:49: error: ‘UnboundScript’ is not a member of ‘v8’
../node_modules/nan/nan_new.h:181:66: error: template argument 1 is invalid
 struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
                                                                  ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:82,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Array>::return_t NanIntern::Factory<v8::Array>::New()’:
../node_modules/nan/nan_implementation_12_inl.h:30:49: error: invalid conversion from ‘v8::Isolate*’ to ‘int’ [-fpermissive]
   return v8::Array::New(v8::Isolate::GetCurrent());
                                                 ^
In file included from /home/ec2-user/.node-gyp/0.11.12/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
/home/ec2-user/.node-gyp/0.11.12/deps/v8/include/v8.h:2335:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(int)’ [-fpermissive]
   static Local<Array> New(int length = 0);
                       ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:82,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Array>::return_t NanIntern::Factory<v8::Array>::New(int)’:
../node_modules/nan/nan_implementation_12_inl.h:35:58: error: no matching function for call to ‘v8::Array::New(v8::Isolate*, int&)’
   return v8::Array::New(v8::Isolate::GetCurrent(), length);
                                                          ^
...
```
