### ISSUE TITLE
centos build error

### ISSUE THREAD

**Issue by jerrywuz** [tugrul/node-mcrypt#19]
```
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
make: Leaving directory `/data/www/bbs/h5web/node_modules/mcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /data/www/bbs/h5web/node_modules/mcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.0.13 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.0.13 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.
```

**Comment by jerrywu55** [comment]
when i use node v0.12.0 on the other  centos server,it build success.

**Comment by tugrul** [comment]
This error log is not explain anything about the error. 

Can you try to build via following command to get verbose error log?

`node-gyp rebuild --release`

**Comment by hhgyu** [comment]
yum install libmcrypt libmcrypt-devel

**Comment by hrajchert** [comment]
I have node 0.11, I run yum install and works great, but node-gyp gives me this

```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1045:12)
gyp ERR! System Linux 3.10.37-47.135.amzn1.x86_64
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /var/www/realtime-api
gyp ERR! node -v v0.11.12
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

**Comment by hrajchert** [comment]
I have this error too, on a amazon ami that is based on centos.
I've tried using yum install, I've tried installing mcrypt and libmcrypt directly....

My log starts with

```
In file included from /home/ec2-user/.node-gyp/0.11.12/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
/home/ec2-user/.node-gyp/0.11.12/deps/v8/include/v8.h: In member function ‘void v8::ReturnValue<T>::Set(uint32_t)’:
/home/ec2-user/.node-gyp/0.11.12/deps/v8/include/v8.h:5816:31: warning: typedef ‘I’ locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
In file included from ../src/mcrypt.h:9:0,
                 from ../src/mcrypt.cc:3:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:70:9: error: ‘UnboundScript’ in namespace ‘v8’ does not name a type
 typedef v8::UnboundScript      NanUnboundScript;
         ^
In file included from ../node_modules/nan/nan.h:82:0,
                 from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
../node_modules/nan/nan_new.h:181:16: error: ‘UnboundScript’ is not a member of ‘v8’
 struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
                ^
```

**Comment by benag** [comment]
same issue on ubuntu

**Comment by tugrul** [comment]
@hrajchert 

This error log not explain anything. Could be incompatible header files, different or old compiler toolchain

**Comment by jaythomas** [comment]
CentOS 6.9 with libmcrypt and libmcrypt-devel installed:
```
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
make: Leaving directory `/srv/engines/webtrader-master/plugins/recognia/node_modules/mcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-696.6.3.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /srv/engines/webtrader-master/plugins/recognia/node_modules/mcrypt
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN recognia-handshake@1.0.0 No repository field.
npm ERR! Linux 2.6.32-696.6.3.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.12 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.12 install script 'node-gyp rebuild --release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
```

**Comment by NHbank** [comment]
I have same problem on Centos 6.9.
In my case resolved with 'sudo' command.

**sudo** npm i mcrypt -g

**Comment by jaythomas** [comment]
Using sudo didn't work for me. The system is fresh and the node installation is pretty vanilla.

I'm not sure if the node module is checking for a globally installed mcrypt, but mcrypt is in the CentOS repos so it seems like it should be using that when it can't compile or checking for that in the first place.
