### ISSUE TITLE
Invalid Key Size

### ISSUE THREAD

**Issue by tonymontana** [tugrul/node-mcrypt#20]
Hi! I'm trying to make work just any of interested algorithms (twofish or aes). It's example from the README, but with another algorithm:
```
var MCrypt = require('mcrypt').MCrypt;

var alg = new MCrypt('twofish', 'cfb');
var iv = alg.generateIv();

alg.open('somekey', iv);

var ciphertext = alg.encrypt('sometext');

console.log(Buffer.concat([iv, ciphertext]).toString('base64'));
```

But it just throw me an error whatever Buffer I try:
```
# node crypt.js 
/home/me/server/crypt.js:6
alg.open('somekey', iv);
    ^
TypeError: Invalid key size. Available key size are [16, 24, 32]
    at TypeError (native)
    at Object.<anonymous> (/home/me/server/crypt.js:6:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I check the Buffer size, it's okay and equals 32 bytes. What am I do wrong?

**Comment by tugrul** [comment]
I tried following code and looks like fine:

```javascript
var mcrypt = require('mcrypt');

var mc = new mcrypt.MCrypt('twofish', 'cfb');

var iv = mc.generateIv();

mc.open('123asdf234324233123asdf234324233');

var ct = mc.encrypt('sometext');

console.log(Buffer.concat([iv, ct]).toString('base64'));
```

Can you check length of your key following script? Maybe your key contains multibyte characters.

```javascript
var bf = new Buffer('somekey');
console.log(bf.length);
```
