### ISSUE TITLE
TypeError: Invalid iv size. You can determine iv size using getIvSize()

### ISSUE THREAD

**Issue by chesstrian** [tugrul/node-mcrypt#21]
Hi,

I use `node-mcrypt` in a node package called `jscryptor` which uses rijndael-128 in cbc mode, with the code in the example:

```js
var password = 'myPassword';
var b64string = "AwHsr+ZD87myaoHm51kZX96u4hhaTuLkEsHwpCRpDywMO1Moz35wdS6OuDgq+SIAK6BOSVKQFSbX/GiFSKhWNy1q94JidKc8hs581JwVJBrEEoxDaMwYE+a+sZeirThbfpup9WZQgp3XuZsGuZPGvy6CvHWt08vsxFAn9tiHW9EFVtdSK7kAGzpnx53OUSt451Jpy6lXl1TKek8m64RT4XPr";

var RNCryptor = require('jscryptor');

console.time('Decrypting example');
var decrypted = RNCryptor.Decrypt(b64string, password);
console.timeEnd('Decrypting example');
console.log("Result:", decrypted);
```

I'm getting the error:

```
RNCryptor.js:221
    mcrypt.open(key, components.headers.iv);
           ^
TypeError: Invalid iv size. You can determine iv size using getIvSize()
    at Object.RNCryptor.Decrypt (/home/chesstrian/WebstormProjects/JSCryptor/lib/RNCryptor.js:221:12)
    at Object.<anonymous> (/home/chesstrian/WebstormProjects/JSCryptor/example.js:7:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

This started happening with `node-mcrypt@v0.0.8`, for that reason `jscryptor` requires `node-mcrypt@v0.0.7`.

What is the reason for this error?, How should I handle it in `jscryptor`?.

Thanks in advance.

**Comment by tugrul** [comment]
IV size could be not same length with algorithm. 

You can survive algorithm's IV size using `getIvSize()` function or you can disable iv size check using `validateIvSize()` function.

https://github.com/tugrul/node-mcrypt#validateivsizeboolean
