### ISSUE TITLE
Error on npm install due to version 2.0 of 'nan' package

### ISSUE THREAD

**Issue by enspencer** [tugrul/node-mcrypt#24]
```
CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.cc:3:
In file included from ../src/mcrypt.h:9:
../../nan/nan.h:111:10: fatal error: 'nan_new.h' file not found
#include "nan_new.h"  // NOLINT(build/include)
         ^
1 error generated.
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/emmaspencer/maxwell-edi/node_modules/mcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
```

**Comment by dylancwood** [comment]
I am also getting the same error on Ubuntu 14.04 as of today. I was able to install and build just fine a couple of days ago.

**Comment by swashcap** [comment]
I’m also seeing similar errors. NPM won’t install the module.

* OS: **Mac 10.10.4**
* IO.js: **v2.5.0**
* NPM: **2.13.1**

Relevant output from NPM:

```shell
> mcrypt@0.0.14 install /Users/creed/Sites/nodeapi/node_modules/mcrypt
> node-gyp rebuild --release

  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:24:16: error: unknown type name '_NAN_METHOD_ARGS_TYPE'; did you mean 'Nan::NAN_METHOD_ARGS_TYPE'?
        MCrypt(_NAN_METHOD_ARGS_TYPE args);
               ^~~~~~~~~~~~~~~~~~~~~
               Nan::NAN_METHOD_ARGS_TYPE
../node_modules/nan/nan.h:1210:48: note: 'Nan::NAN_METHOD_ARGS_TYPE' declared here
typedef const FunctionCallbackInfo<v8::Value>& NAN_METHOD_ARGS_TYPE;
                                               ^
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:64:9: error: unknown type name 'NanAsciiString'
        NanAsciiString algo;
        ^
../src/mcrypt.h:65:9: error: unknown type name 'NanAsciiString'
        NanAsciiString mode;
        ^
../src/mcrypt.h:66:9: error: unknown type name 'NanAsciiString'
        NanAsciiString algoDir; 
        ^
../src/mcrypt.h:67:9: error: unknown type name 'NanAsciiString'
        NanAsciiString modeDir;
        ^
../src/mcrypt.cc:9:16: error: unknown type name '_NAN_METHOD_ARGS_TYPE'; did you mean 'Nan::NAN_METHOD_ARGS_TYPE'?
MCrypt::MCrypt(_NAN_METHOD_ARGS_TYPE args): 
               ^~~~~~~~~~~~~~~~~~~~~
               Nan::NAN_METHOD_ARGS_TYPE
../node_modules/nan/nan.h:1210:48: note: 'Nan::NAN_METHOD_ARGS_TYPE' declared here
typedef const FunctionCallbackInfo<v8::Value>& NAN_METHOD_ARGS_TYPE;
                                               ^
../src/mcrypt.cc:94:5: error: use of undeclared identifier 'NanScope'
    NanScope();
    ^
../src/mcrypt.cc:96:10: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if (!args.IsConstructCall()) {
         ^~~~
         uv_process_options_s::args
/Users/creed/.node-gyp/2.5.0/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/mcrypt.cc:96:10: error: invalid use of member 'args' in static member function
    if (!args.IsConstructCall()) {
         ^~~~
../src/mcrypt.cc:97:32: error: use of undeclared identifier 'args'; did you mean 'argv'?
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                               ^~~~
                               argv
../src/mcrypt.cc:97:22: note: 'argv' declared here
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                     ^
../src/mcrypt.cc:97:41: error: use of undeclared identifier 'args'; did you mean 'argv'?
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                                        ^~~~
                                        argv
../src/mcrypt.cc:97:22: note: 'argv' declared here
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                     ^
../src/mcrypt.cc:97:50: error: use of undeclared identifier 'args'; did you mean 'argv'?
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                                                 ^~~~
                                                 argv
../src/mcrypt.cc:97:22: note: 'argv' declared here
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                     ^
../src/mcrypt.cc:97:59: error: use of undeclared identifier 'args'; did you mean 'argv'?
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                                                          ^~~~
                                                          argv
../src/mcrypt.cc:97:22: note: 'argv' declared here
        Local<Value> argv[] = {args[0], args[1], args[2], args[3]};
                     ^
../src/mcrypt.cc:98:32: error: use of undeclared identifier 'NanNew'
        Local<Function> cons = NanNew<Function>(constructor);
                               ^
../src/mcrypt.cc:98:39: error: 'Function' does not refer to a value
        Local<Function> cons = NanNew<Function>(constructor);
                                      ^
/Users/creed/.node-gyp/2.5.0/deps/v8/include/v8.h:2899:17: note: declared here
class V8_EXPORT Function : public Object {
                ^
../src/mcrypt.cc:99:9: error: use of undeclared identifier 'NanReturnValue'
        NanReturnValue(cons->NewInstance(4, argv));
        ^
../src/mcrypt.cc:102:9: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if (args.Length() < 2) {
        ^~~~
        uv_process_options_s::args
/Users/creed/.node-gyp/2.5.0/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/mcrypt.cc:102:9: error: invalid use of member 'args' in static member function
    if (args.Length() < 2) {
        ^~~~
../src/mcrypt.cc:103:9: error: use of undeclared identifier 'NanThrowTypeError'; did you mean 'Nan::ThrowTypeError'?
        NanThrowTypeError("Missing parameters. Algorithm and mode should be specified.");
        ^~~~~~~~~~~~~~~~~
        Nan::ThrowTypeError
../node_modules/nan/nan.h:635:3: note: 'Nan::ThrowTypeError' declared here
  X(TypeError)
  ^
../node_modules/nan/nan.h:619:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:209:1: note: expanded from here
ThrowTypeError
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by dylancwood** [comment]
Just a suggestion: maybe the following change to `package.json`:

```
"nan": "~1.9.0"
```

**Comment by cansozeri** [comment]
Same over here for Ubuntu 14.04...

**Comment by tugrul** [comment]
I published quick fix of @lcarsos. I'm going to refactor for new nan.

**Comment by cansozeri** [comment]
I have installed mcrypt after installed nan 1.9.0 and it works : )

**Comment by tugrul** [comment]
I published npm release for this issue

**Comment by tugrul** [comment]
I published `mcrypt@0.1.6`

**Comment by tugrul** [comment]
@enspencer @swashcap @cansozeri is resolved?

**Comment by swashcap** [comment]
@tugrul Yep, it installs fine now. Thanks! :+1:
