### ISSUE TITLE
Issue on install Ubuntu 14.04

### ISSUE THREAD

**Issue by sylvainlap** [tugrul/node-mcrypt#37]
Hi,

I'm trying to install mcrypt@0.1, and I got this error:
```
npm install mcrypt
/
> mcrypt@0.1.4 install /home/sylvainlap/DEV/WORKSPACE/mc/node_modules/mcrypt
> node-gyp rebuild --release

gyp: lib/libmcrypt/libmcrypt.gyp not found (cwd: /home/sylvainlap/DEV/WORKSPACE/mc/node_modules/mcrypt) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-50-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/sylvainlap/DEV/WORKSPACE/mc/node_modules/mcrypt
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.16.0-50-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mcrypt"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.4 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.4 install script 'node-gyp rebuild --release'.
npm ERR! This is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

> mcrypt@0.1.4 preuninstall /home/sylvainlap/DEV/WORKSPACE/mc/node_modules/mcrypt
> rm -rf build/*


npm ERR! Please include the following file with any support request:
npm ERR!     /home/sylvainlap/DEV/WORKSPACE/mc/npm-debug.log
```
My env is: node v4.2.1, node-gyp v3.0.3, npm v2.14.7
libmcrypt4 is installed
```
sudo apt-get install libmcrypt4 libmcrypt-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libmcrypt-dev est déjà la plus récente version disponible.
libmcrypt4 est déjà la plus récente version disponible.
```

**Comment by tugrul** [comment]
I published again with dependency library

**Comment by sylvainlap** [comment]
fixed ! good job !
