### ISSUE TITLE
Unable to Install mcrypt locally without sudo

### ISSUE THREAD

**Issue by jamilnyc** [tugrul/node-mcrypt#53]
Node Version: 6.0.0.
NPM Version: 3.8.6
OS: CentOS release 6.7 (Final)

When running `npm install mcrypt` I get a lot of C/C++ errors for the `nan` module. 

The very first error is:

```
AR(target) Release/obj.target/lib/libmcrypt/mcrypt.a
  COPY Release/mcrypt.a
  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
In file included from ../src/mcrypt.h:9,
                 from ../src/mcrypt.cc:3:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```

Then at the bottom of the output:

```
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
make: Leaving directory `/home/vagrant/testNodeProject/node_modules/mcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-573.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/vagrant/testNodeProject/node_modules/mcrypt
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/testNodeProject/package.json'
npm WARN testNodeProject No description
npm WARN testNodeProject No repository field.
npm WARN testNodeProject No README data
npm WARN testNodeProject No license field.
npm ERR! Linux 2.6.32-573.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mcrypt"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.10 install: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.10 install script 'node-gyp rebuild --release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/testNodeProject/npm-debug.log
```

If I run this with `sudo` it installs without errors. I am not doing a global install. I also cannot execute any script that I `require` the `mcrypt` module in without sudo either.

**Comment by tugrul** [comment]
I don't know CentOS but maybe there is an alternatives of c++ compiler for each user environment.

```../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler```

Can you compare versions of c++ compilers like `c++ --version` and `sudo c++ --version`

**Comment by jamilnyc** [comment]
Thanks for responding @tugrul 

The compiler version is the same for `sudo` and regular users also for c++ and g++.

```
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tugrul** [comment]
This is error message depended to compiler environment.

https://github.com/nodejs/nan/blob/master/nan.h#L42

**Comment by jamilnyc** [comment]
That is weird. It requires c++ version greater than `201103L`, but I have `20120313`

**Comment by tugrul** [comment]
same issue #57
