### ISSUE TITLE
 Error: mcrypt@0.1.12 install: `node-gyp rebuild --release`

### ISSUE THREAD

**Issue by adamchenwei** [tugrul/node-mcrypt#62]
```
1051 warn optional Skipping failed optional dependency /chokidar/fsevents:
1052 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.17
1053 warn babel-loader@6.2.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
1054 verbose stack Error: mcrypt@0.1.12 install: `node-gyp rebuild --release`
1054 verbose stack Exit status 1
1054 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
1054 verbose stack     at emitTwo (events.js:106:13)
1054 verbose stack     at EventEmitter.emit (events.js:191:7)
1054 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
1054 verbose stack     at emitTwo (events.js:106:13)
1054 verbose stack     at ChildProcess.emit (events.js:191:7)
1054 verbose stack     at maybeClose (internal/child_process.js:852:16)
1054 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
1055 verbose pkgid mcrypt@0.1.12
1056 verbose cwd /home/vagrant/priceline-web/m-fly-search
1057 error Linux 3.10.0-514.2.2.el7.x86_64
1058 error argv "/usr/bin/node" "/usr/bin/npm" "install" "mcrypt"
1059 error node v6.3.1
1060 error npm  v3.10.3
1061 error code ELIFECYCLE
1062 error mcrypt@0.1.12 install: `node-gyp rebuild --release`
1062 error Exit status 1
1063 error Failed at the mcrypt@0.1.12 install script 'node-gyp rebuild --release'.
1063 error Make sure you have the latest version of node.js and npm installed.
1063 error If you do, this is most likely a problem with the mcrypt package,
1063 error not with npm itself.
1063 error Tell the author that this fails on your system:
1063 error     node-gyp rebuild --release
1063 error You can get information on how to open an issue for this project with:
1063 error     npm bugs mcrypt
1063 error Or if that isn't available, you can get their info via:
1063 error     npm owner ls mcrypt
1063 error There is likely additional logging output above.
1064 verbose exit [ 1, true ]
```

**Comment by simondutertre** [comment]
Save issue error : 
npm ERR! mcrypt@0.1.12 install: `node-gyp rebuild --release`
npm ERR! Exit status 1

On macOs

**Comment by anhnguyen72** [comment]
Try to use node version 8.11.1
