### ISSUE TITLE
(macos catalina) npm install mcrypt fails - vector.h not found

### ISSUE THREAD

**Issue by himanshusinghs** [tugrul/node-mcrypt#85]
### Environment specifications
- macOs Catalina (Version 10.15.2)
- Xcode Version 11.3.1 (11C504)
- Node installed using [nvm](https://github.com/nvm-sh/nvm)
  - Node Version - v6.17.1
  - npm version - v3.10.10

### Debug log towards the end of npm install
```
> mcrypt@0.1.17 install /Users/himanshusinghs/PSource/@ninox/ums/node_modules/mcrypt
> node-gyp rebuild

  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/3-way.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/arcfour.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/blowfish.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/blowfish-compat.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/cast-128.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/cast-256.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/des.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/enigma.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/gost.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/loki97.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/panama.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/rc2.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/rijndael-128.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/rijndael-192.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/rijndael-256.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/safer64.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/safer128.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/saferplus.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/serpent.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/tripledes.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/twofish.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/wake.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/algorithms/xtea.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/cbc.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/cfb.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/ctr.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/ecb.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/ncfb.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/nofb.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/ofb.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/modules/modes/stream.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/lib/bzero.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/lib/mcrypt.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/lib/mcrypt_extra.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/lib/mcrypt_modules.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/lib/mcrypt_symb.o
  CC(target) Release/obj.target/libmcrypt/lib/libmcrypt/lib/xmemory.o
  LIBTOOL-STATIC Release/mcrypt.a
  CXX(target) Release/obj.target/mcrypt/src/mcrypt.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/mcrypt.cc:3:
../src/mcrypt.h:5:10: fatal error: 'vector' file not found
#include <vector> 
         ^~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/mcrypt/src/mcrypt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/himanshusinghs/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/Users/himanshusinghs/.nvm/versions/node/v6.17.1/bin/node" "/Users/himanshusinghs/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/himanshusinghs/PSource/@ninox/ums/node_modules/mcrypt
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 19.2.0
npm ERR! argv "/Users/himanshusinghs/.nvm/versions/node/v6.17.1/bin/node" "/Users/himanshusinghs/.nvm/versions/node/v6.17.1/bin/npm" "install" "mcrypt"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mcrypt@0.1.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mcrypt@0.1.17 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/himanshusinghs/PSource/@ninox/ums/npm-debug.log
```

From what I see from debug log all I can understand is that vector.h, a dependency is missing on my system. Have already installed command line tools and using homebrew installed mcrypt already.

Not sure what to do next to solve this.

**Comment by himanshusinghs** [comment]
@tugrul Any comment on this behaviour?

**Comment by tugrul** [comment]
Did you try to use https://github.com/tugrul/cryptian

**Comment by himanshusinghs** [comment]
No I haven't yet. Will try that and report as soon as I something with that.

**Comment by himanshusinghs** [comment]
Haven't finished testing this yet. Feel free to close, I will reopen once I am on it again.
